// Catálogo de códigos de error del dominio.
export const ERROR_CODES = Object.freeze({
    // Validación datos de entrada
    VALIDATION_ERROR: 'VALIDATION_ERROR',

    // Recursos que no existen
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    DELIVERY_NOT_FOUND: 'DELIVERY_NOT_FOUND',

    // Regla de negocio de Users
    DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    INVALID_ROLE: 'INVALID_ROLE',

    // Regla de negocio de Orders
    ORDER_LOCKED: 'ORDER_LOCKED',

    // Regla de negocio de Products
    INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',

    // Regla de negocio de Deliveries
    INVALID_DELIVERY_STATUS: 'INVALID_DELIVERY_STATUS',
    INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
    INVALID_DELIVERY_PRIORITY: 'INVALID_DELIVERY_PRIORITY',
    DELIVERY_NOT_PENDING: 'DELIVERY_NOT_PENDING',

    // Módulo de mocking
    INVALID_MOCK_QTY: 'INVALID_MOCK_QTY',
    INVALID_MOCK_COLLECTION: 'INVALID_MOCK_COLLECTION',
    MOCK_SEED_FAILED: 'MOCK_SEED_FAILED',

    // Infraestructura
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    CAST_ERROR: 'CAST_ERROR',
    DUPLICATE_KEY: 'DUPLICATE_KEY',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
})

export default ERROR_CODES